# netlify configuration
[build]
base = "site/"
publish = "public/"
command = "make build"

[build.environment]
HUGO_VERSION = "0.125.7"

[context.production.environment]
# this controls our robots.txt
HUGO_ENV = "production"
HUGO_BASEURL = "https://kwok.sigs.k8s.io/"

# Standard Netlify redirects
[[redirects]]
    from = "https://k8s-kwok.netlify.com/*"
    to = "https://kwok.sigs.k8s.io/:splat"
    status = 301
    force = true

[[redirects]]
    from = "https://kwok-demo.netlify.com/*"
    to = "https://kwok.sigs.k8s.io/:splat"
    status = 301
    force = true
