{{ if .Values.enableDeployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kwok.fullname" . }}
  labels:
    {{- include "kwok.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "kwok.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kwok.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kwok.fullname" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        args:
        - --config=/root/.kwok/kwok.yaml
        - --node-ip=$(POD_IP)
        env:
          {{ toYaml .Values.env | nindent 10 }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz
            port: {{ .Values.server.port }}
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: {{ .Values.server.port }}
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 20
          timeoutSeconds: 2
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: {{ .Values.server.port }}
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          timeoutSeconds: 2
        volumeMounts:
        - name: kwok-config
          subPath: kwok.yaml
          mountPath: /root/.kwok/kwok.yaml
          readOnly: true
        {{- range .Values.volumeMounts }}
        - {{- . | toYaml | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      volumes:
      - name: kwok-config
        configMap:
          name: {{ include "kwok.fullname" . }}
      {{- range .Values.volumes }}
      - {{- . | toYaml | nindent 8 }}
      {{- end }}
{{ end }}
