apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/kwok.x-k8s.io_logs.yaml
- bases/kwok.x-k8s.io_clusterlogs.yaml
- bases/kwok.x-k8s.io_attaches.yaml
- bases/kwok.x-k8s.io_clusterattaches.yaml
- bases/kwok.x-k8s.io_execs.yaml
- bases/kwok.x-k8s.io_clusterexecs.yaml
- bases/kwok.x-k8s.io_portforwards.yaml
- bases/kwok.x-k8s.io_clusterportforwards.yaml
- bases/kwok.x-k8s.io_custommetrics.yaml
- bases/kwok.x-k8s.io_externalmetrics.yaml
- bases/kwok.x-k8s.io_metrics.yaml
- bases/kwok.x-k8s.io_stages.yaml
