apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwok-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kwok-controller
  template:
    metadata:
      name: kwok-controller
      namespace: kube-system
      labels:
        app: kwok-controller
    spec:
      containers:
        - name: kwok-controller
          image: registry.k8s.io/kwok/kwok
          imagePullPolicy: IfNotPresent
          args:
            - --manage-all-nodes=false
            - --manage-nodes-with-annotation-selector=kwok.x-k8s.io/node=fake
            - --manage-nodes-with-label-selector=
            - --disregard-status-with-annotation-selector=kwok.x-k8s.io/status=custom
            - --disregard-status-with-label-selector=
            - --server-address=0.0.0.0:8080
            - --node-ip=$(POD_IP)
            - --cidr=10.0.0.1/24
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 2
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 2
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 5
      serviceAccount: kwok-controller
      serviceAccountName: kwok-controller
      restartPolicy: Always
