apiVersion: v2
description: Default stage policy of KWOK (Kubernetes WithOut Kubelet)
type: application
home: https://kwok.sigs.k8s.io
icon: https://github.com/kubernetes-sigs/kwok/raw/main/logo/kwok.png
keywords:
- kubernetes
- kwok
- kwok stage policy
sources:
- https://github.com/kubernetes-sigs/kwok
name: stage-fast
maintainers:
- name: wzshiming
  email: wzshiming@hotmail.com
appVersion: v0.7.0
version: 0.2.0
