apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwok-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kwok-controller
  template:
    metadata:
      name: kwok-controller
      namespace: kube-system
      labels:
        app: kwok-controller
    spec:
      containers:
        - name: kwok-controller
          securityContext:
            capabilities:
              add:
                - ALL
          args:
            - --manage-all-nodes=false
            - --manage-nodes-with-annotation-selector=kwok.x-k8s.io/node=fake
            - --manage-nodes-with-label-selector=
            - --disregard-status-with-annotation-selector=kwok.x-k8s.io/status=custom
            - --disregard-status-with-label-selector=
            - --node-ip=$(POD_IP)
            - --node-port=10247
            - --node-lease-duration-seconds=40
            - --experimental-enable-cni=true
          volumeMounts:
            - name: etc-cni
              mountPath: /etc/cni
            - name: opt-cni
              mountPath: /opt/cni
            - name: var-lib-cni
              mountPath: /var/lib/cni
            - name: var-run-netns
              mountPath: /var/run/netns
      volumes:
        - name: etc-cni
          hostPath:
            path: /etc/cni
        - name: opt-cni
          hostPath:
            path: /opt/cni
        - name: var-lib-cni
          hostPath:
            path: /var/lib/cni
        - name: var-run-netns
          hostPath:
            path: /var/run/netns
