apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: node-heartbeat-with-lease
spec:
  resourceRef:
    apiGroup: v1
    kind: Node
  selector:
    matchExpressions:
    - key: '.status.phase'
      operator: 'In'
      values:
      - 'Running'
    - key: '.status.conditions.[] | select( .type == "Ready" ) | .status'
      operator: 'In'
      values:
      - 'True'
  delay:
    durationMilliseconds: 600000
    jitterDurationMilliseconds: 610000
  next:
    statusTemplate: |
      {{ `{{ $now := Now }}` }}
      {{ `{{ $lastTransitionTime := or .metadata.creationTimestamp $now }}` }}
      conditions:
      {{ `{{ range NodeConditions }}` }}
      - lastHeartbeatTime: {{ `{{ $now | Quote }}` }}
        lastTransitionTime: {{ `{{ $lastTransitionTime | Quote }}` }}
        message: {{ `{{ .message | Quote }}` }}
        reason: {{ `{{ .reason | Quote }}` }}
        status: {{ `{{ .status | Quote }}` }}
        type: {{ `{{ .type | Quote }}` }}
      {{ `{{ end }}` }}

      addresses:
      {{ `{{ with .status.addresses }}` }}
      {{ `{{ YAML . 1 }}` }}
      {{ `{{ else }}` }}
      {{ `{{ with NodeIP }}` }}
      - address: {{ `{{ . | Quote }}` }}
        type: InternalIP
      {{ `{{ end }}` }}
      {{ `{{ with NodeName }}` }}
      - address: {{ `{{ . | Quote }}` }}
        type: Hostname
      {{ `{{ end }}` }}
      {{ `{{ end }}` }}

      {{ `{{ with NodePort }}` }}
      daemonEndpoints:
        kubeletEndpoint:
          Port: {{ `{{ . }}` }}
      {{ `{{ end }}` }}
