apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-ready
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - key: '.metadata.deletionTimestamp'
      operator: 'DoesNotExist'
    - key: '.status.phase'
      operator: 'In'
      values:
      - 'Pending'
    - key: '.status.podIP'
      operator: 'DoesNotExist'
  next:
    statusTemplate: |
      {{ `{{ $now := Now }}` }}

      conditions:
      - lastTransitionTime: {{ `{{ $now | Quote }}` }}
        status: "True"
        type: Initialized
      - lastTransitionTime: {{ `{{ $now | Quote }}` }}
        status: "True"
        type: Ready
      - lastTransitionTime: {{ `{{ $now | Quote }}` }}
        status: "True"
        type: ContainersReady
      {{ `{{ range .spec.readinessGates }}` }}
      - lastTransitionTime: {{ `{{ $now | Quote }}` }}
        status: "True"
        type: {{ `{{ .conditionType | Quote }}` }}
      {{ `{{ end }}` }}

      containerStatuses:
      {{ `{{ range .spec.containers }}` }}
      - image: {{ `{{ .image | Quote }}` }}
        name: {{ `{{ .name | Quote }}` }}
        ready: true
        restartCount: 0
        state:
          running:
            startedAt: {{ `{{ $now | Quote }}` }}
      {{ `{{ end }}` }}

      initContainerStatuses:
      {{ `{{ range .spec.initContainers }}` }}
      - image: {{ `{{ .image | Quote }}` }}
        name: {{ `{{ .name | Quote }}` }}
        ready: true
        restartCount: 0
        {{ `{{ if eq .restartPolicy "Always" }}` }}
        started: true
        state:
          running:
            startedAt: {{ `{{ $now | Quote }}` }}
        {{ `{{ else }}` }}
        state:
          terminated:
            exitCode: 0
            finishedAt: {{ `{{ $now | Quote }}` }}
            reason: Completed
            startedAt: {{ `{{ $now | Quote }}` }}
        {{ `{{ end }}` }}
      {{ `{{ end }}` }}

      hostIP: {{ `{{ NodeIPWith .spec.nodeName | Quote }}` }}
      podIP: {{ `{{ PodIPWith .spec.nodeName ( or .spec.hostNetwork false ) ( or .metadata.uid "" ) ( or .metadata.name "" ) ( or .metadata.namespace "" ) | Quote }}` }}
      phase: Running
      startTime: {{ `{{ $now | Quote }}` }}
